### ISSUE TITLE
[Rss2Email] Semaphore

### ISSUE THREAD

**Issue by pavel-b-novikov** [allyna-mozhina/nsudotnet#1]
Вы или обоснуйте использование семафора(1,1), или переделайте.

Ну и в довесок - вот этот вот кусок кода:

``` C#
 _smtpGuard.WaitOne();

foreach (var item in items)
{
 if (item.Date > _lastSent)
 {
  SendItem(item, Recipient);
 }
}
_lastSent = items.Last().Date;

_smtpGuard.Release();
```

Вы в нем проблем никаких не видите, например?

**Comment by allyna-mozhina** [comment]
Для периодической проверки фида я пользую Timer, который генерит событие Elapsed и вешаю на это событие обработчик. Если задать слишком маленькое время проверки, то одновременно могут работать несколько обработчиков в разных потоках, а _smtpClient у меня один и у него нельзя дергать Send, пока не завершилась предыдущая отправка. Соответственно, на пользование им выстраиваем очередь на семафоре.

Может смущать определение _lastSent, оно так выглядит в силу допущений, что работаем с одним фидом, из которого элементы не удаляются и не добавляются задним числом. Или с семафором проблема?

**Comment by pavel-b-novikov** [comment]
Ну то есть по факту у вас одноместный примитив синхронизации тут должен быть?
А одноместный примитив синхронизации у нас как называется?
А проблема в куске кода не конкретно с семафором, а с политикой его использования.

**Comment by allyna-mozhina** [comment]
Ну да, мутекс здесь уместнее. Если заменить на него семафор проблема останется?

**Comment by pavel-b-novikov** [comment]
останется

21 мая 2015 г., 18:49 пользователь Алина Можина notifications@github.com
написал:

> Ну да, мутекс здесь уместнее. Если заменить на него семафор проблема
> останется?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allyna-mozhina/nsudotnet/issues/1#issuecomment-104258142
> .

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by allyna-mozhina** [comment]
Разве что лочить примитив ближе к использованию ресурса, если сходу про политику использования думать. Хотя мне нужно согласованное состояние _lastSent еще, так что не пойдет. Прошу наводку.

**Comment by pavel-b-novikov** [comment]
SMTP-сервер может быть тупо оффлайн 10 минут

**Comment by allyna-mozhina** [comment]
Исправлено

**Comment by allyna-mozhina** [comment]
Обновлено
