### ISSUE TITLE
[Rss2Email] Сыграем в одну игру

### ISSUE THREAD

**Issue by pavel-b-novikov** [allyna-mozhina/nsudotnet#3]
Я вижу амбициозненький код вкупе с его малым количеством.

По сему, предлагаю такую замечательную идею: я вам поднимаю количество баллов за эту задачу до 9, а вы взамен переделываете почту с б-гомерзского Net.Mail на MVCMailer (это сделать будет непросто, количество баллов как бы намекает) и описываете потом впечатления?

**Comment by allyna-mozhina** [comment]
Рубрика "Эксперименты" - это хорошо, но за день до дедлайна опасно. Постараюсь вечером оценить реальность сего мероприятия и если что доделаю начатую Enigm'у.

**Comment by pavel-b-novikov** [comment]
Добро

21 мая 2015 г., 19:06 пользователь Алина Можина notifications@github.com
написал:

> Рубрика "Эксперименты" - это хорошо, но за день до дедлайна опасно.
> Постараюсь вечером оценить реальность сего мероприятия и если что доделаю
> начатую Enigm'у.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allyna-mozhina/nsudotnet/issues/3#issuecomment-104268798
> .

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by allyna-mozhina** [comment]
Я правильно понимаю, что нужно поднимать ASP .NET MVC приложение, чтобы использовать MVCMailer? Форвардер без морды плохо ложится на MVC. Разве что хранить во Views master pages и view для писем, в Models сущности для RSS, но куда складывать существующую логику? Это ведь не контроллер.

**Comment by pavel-b-novikov** [comment]
Ненене. Суть в том, чтобы не поднимать Web-приложение.

21 мая 2015 г., 22:08 пользователь Алина Можина notifications@github.com
написал:

> Я правильно понимаю, что нужно поднимать ASP .NET MVC приложение, чтобы
> использовать MVCMailer? Форвардер без морды плохо ложится на MVC. Разве что
> хранить во Views master pages и view для писем, в Models сущности для RSS,
> но куда складывать существующую логику? Это ведь не контроллер.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allyna-mozhina/nsudotnet/issues/3#issuecomment-104334823
> .

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by pavel-b-novikov** [comment]
Ну т.е. запускать его точно не надо будет. Подобает использовать
возможности Razor вне контекста Web-приложения.

21 мая 2015 г., 23:20 пользователь Pavel Novikov pavel.b.novikov@gmail.com
написал:

> Ненене. Суть в том, чтобы не поднимать Web-приложение.
> 
> 21 мая 2015 г., 22:08 пользователь Алина Можина notifications@github.com
> написал:
> 
> > Я правильно понимаю, что нужно поднимать ASP .NET MVC приложение, чтобы
> > использовать MVCMailer? Форвардер без морды плохо ложится на MVC. Разве что
> > хранить во Views master pages и view для писем, в Models сущности для RSS,
> > но куда складывать существующую логику? Это ведь не контроллер.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/allyna-mozhina/nsudotnet/issues/3#issuecomment-104334823
> > .
> 
> ## 
> 
> Sincerelly yours,
> Pavel B. Novikov
> Skype: nsu_the_cjay
> Phone: +7 961 872 5447

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by allyna-mozhina** [comment]
Сделано

**Comment by pavel-b-novikov** [comment]
Добила-таки. 
С помощью моего кода, такой-то матери и мучений, добила.
Молодец, держи 9, зачет твой.
